"""Manage generated hotkey artifacts from the human-owned SQLite catalog.

Human workflow:
  1. Edit platforms/shared/data/hotkeys.db with a SQLite editor.
  2. Run: python ai/hotkey_sync.py --sync

AI/reviewer workflow:
  python ai/hotkey_sync.py --check
  python ai/hotkey_sync.py --list

Source of truth: platforms/shared/data/hotkeys.db
Generated artifacts: platforms/windows/hotkeys/*.ahk, platforms/windows/hotkeys/README.md,
and platforms/macos/hammerspoon/generated/bindings.lua
"""

from __future__ import annotations

import argparse
import json
import re
import sqlite3
import sys
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).parent.parent
DB_PATH = ROOT / "platforms" / "shared" / "data" / "hotkeys.db"
HOTKEYS_DIR = ROOT / "platforms" / "windows" / "hotkeys"
README_PATH = HOTKEYS_DIR / "README.md"
GENERATED_MARKER = "; AUTO-GENERATED by ai/hotkey_sync.py"

MACOS_BINDINGS_PATH = ROOT / "platforms" / "macos" / "hammerspoon" / "generated" / "bindings.lua"
MACOS_HOTSTRING_PROFILES_PATH = ROOT / "platforms" / "macos" / "hammerspoon" / "generated" / "hotstring_profiles.lua"
WINDOWS_DATA_DIR = ROOT / "platforms" / "windows" / "data"
LUA_GENERATED_MARKER = "-- AUTO-GENERATED by ai/hotkey_sync.py"

DB_SCHEMA = """
CREATE TABLE IF NOT EXISTS hotkeys (
    sort_order    INTEGER,
    id            TEXT PRIMARY KEY,
    file          TEXT NOT NULL,
    type          TEXT NOT NULL,
    key           TEXT,
    trigger       TEXT,
    options       TEXT,
    windows_context TEXT,
    context_label   TEXT,
    action          TEXT NOT NULL,
    label           TEXT NOT NULL,
    platform        TEXT NOT NULL,
    active          INTEGER NOT NULL DEFAULT 1,
    portability     TEXT NOT NULL DEFAULT 'windows-only'
);

CREATE TABLE IF NOT EXISTS hotstring_profiles (
    sort_order    INTEGER NOT NULL UNIQUE,
    id            TEXT PRIMARY KEY,
    mode          TEXT NOT NULL,
    context_label TEXT NOT NULL,
    platform      TEXT NOT NULL,
    active        INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS hotstring_entries (
    profile_id  TEXT NOT NULL REFERENCES hotstring_profiles(id),
    sort_order  INTEGER NOT NULL,
    trigger     TEXT NOT NULL,
    value       TEXT NOT NULL,
    immediate   INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (profile_id, trigger),
    UNIQUE (profile_id, sort_order)
);
"""

DB_COLUMNS = [
    "sort_order", "id", "file", "type", "key", "trigger", "options",
    "windows_context", "context_label",
    "action", "label", "platform", "active", "portability",
]

LEGACY_HOTKEY_COLUMNS = [
    "sort_order", "id", "file", "type", "key", "trigger", "options",
    "context", "context_fn", "context_label",
    "action", "label", "platform", "active", "notes", "portability",
]

HOTKEYS_TABLE_SCHEMA = """
CREATE TABLE hotkeys (
    sort_order      INTEGER,
    id              TEXT PRIMARY KEY,
    file            TEXT NOT NULL,
    type            TEXT NOT NULL,
    key             TEXT,
    trigger         TEXT,
    options         TEXT,
    windows_context TEXT,
    context_label   TEXT,
    action          TEXT NOT NULL,
    label           TEXT NOT NULL,
    platform        TEXT NOT NULL,
    active          INTEGER NOT NULL DEFAULT 1,
    portability     TEXT NOT NULL DEFAULT 'windows-only'
)
"""

FILE_HEADERS = {
    "sap-gui": "; SAP GUI triggers only; implementation lives in library/automation/sap.ahk.",
    "sap-eclipse": "; SAP ADT/Eclipse triggers only; implementation lives in library/automation/sap.ahk.",
}

FILE_TITLES = {
    "global": "Global",
    "sap-gui": "SAP GUI and NWBC",
    "sap-eclipse": "SAP Eclipse / ADT",
    "domains/productivity": "Productivity workflows",
}

FILE_ORDER = {name: i for i, name in enumerate(FILE_TITLES)}
FILE_KEY_RE = re.compile(r"^[a-z0-9][a-z0-9/-]*$")
SAP_TCODE_ACTION_PREFIX = "sap-tcode:"
SAP_TCODE_RE = re.compile(r"^[A-Za-z0-9._/-]+$")


class CatalogError(RuntimeError):
    pass


def _row_to_entry(row: tuple[object, ...]) -> dict[str, object]:
    entry = dict(zip(DB_COLUMNS, row))
    try:
        entry["platform"] = json.loads(entry["platform"])
    except (TypeError, json.JSONDecodeError) as exc:
        raise CatalogError(f"Invalid JSON fields for hotkey {entry.get('id')}: {exc}") from exc
    entry["active"] = bool(entry["active"])
    return entry


def create_db() -> None:
    if DB_PATH.exists():
        raise CatalogError(f"Refusing to replace existing human catalog: {DB_PATH}")
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    with sqlite3.connect(DB_PATH) as connection:
        connection.executescript(DB_SCHEMA)
    print(f"Created empty catalog: {DB_PATH}")


def migrate_hotkeys_schema() -> None:
    if not DB_PATH.exists():
        raise CatalogError(f"Human catalog not found: {DB_PATH}")

    with sqlite3.connect(DB_PATH) as connection:
        columns = [row[1] for row in connection.execute("PRAGMA table_info(hotkeys)")]
        if columns == DB_COLUMNS:
            print("Hotkey schema is already current.")
            return
        if columns != LEGACY_HOTKEY_COLUMNS:
            raise CatalogError(
                "Unexpected legacy hotkeys schema. Expected columns: "
                + ", ".join(LEGACY_HOTKEY_COLUMNS)
            )

        connection.execute("BEGIN IMMEDIATE")
        old_count = connection.execute("SELECT COUNT(*) FROM hotkeys").fetchone()[0]
        old_ids = {row[0] for row in connection.execute("SELECT id FROM hotkeys")}
        connection.execute("ALTER TABLE hotkeys RENAME TO hotkeys_legacy")
        connection.execute(HOTKEYS_TABLE_SCHEMA)
        connection.execute(
            """
            INSERT INTO hotkeys (
                sort_order, id, file, type, key, trigger, options,
                windows_context, context_label, action, label,
                platform, active, portability
            )
            SELECT
                sort_order, id, file, type, key, trigger, options,
                CASE
                    WHEN COALESCE(context_fn, '') != '' THEN context_fn
                    WHEN COALESCE(context, '') != '' THEN 'winactive(' || context || ')'
                    ELSE NULL
                END,
                context_label, action, label, platform, active, portability
            FROM hotkeys_legacy
            """
        )
        new_count = connection.execute("SELECT COUNT(*) FROM hotkeys").fetchone()[0]
        new_ids = {row[0] for row in connection.execute("SELECT id FROM hotkeys")}
        invalid_contexts = connection.execute(
            "SELECT id FROM hotkeys WHERE windows_context LIKE '#hotif%'"
        ).fetchall()
        if new_count != old_count or new_ids != old_ids or invalid_contexts:
            raise CatalogError("Hotkey schema migration failed its data-preservation checks.")
        connection.execute("DROP TABLE hotkeys_legacy")

    print(f"Migrated {old_count} hotkeys to the current schema.")


def migrate_hotstring_profiles() -> None:
    profiles = [
        ("autocorrect", "replace", "global", ["windows", "macos"]),
        ("quick-snippets", "replace", "global", ["windows", "macos"]),
        ("sap-transaction-shortcuts", "sap-command", "sap-gui-session", ["windows", "macos"]),
        ("sap-transaction-catalog", "sap-command", "sap-gui-session", ["windows", "macos"]),
        ("ymt-commands", "sap-command", "sap-gui-session", ["windows", "macos"]),
    ]
    with sqlite3.connect(DB_PATH) as connection:
        connection.executescript(DB_SCHEMA)
        existing = connection.execute("SELECT COUNT(*) FROM hotstring_profiles").fetchone()[0]
        if existing:
            raise CatalogError("Refusing to overwrite existing hotstring profile catalog.")
        for profile_order, (profile_id, mode, context_label, platform) in enumerate(profiles):
            source_path = WINDOWS_DATA_DIR / f"{profile_id}.json"
            payload = json.loads(source_path.read_text(encoding="utf-8"))
            items = payload.get("items")
            if not isinstance(items, list) or not items:
                raise CatalogError(f"{source_path}: expected non-empty items[]")
            connection.execute(
                "INSERT INTO hotstring_profiles "
                "(sort_order, id, mode, context_label, platform, active) VALUES (?, ?, ?, ?, ?, 1)",
                (profile_order, profile_id, mode, context_label, json.dumps(platform)),
            )
            for entry_order, item in enumerate(items):
                trigger = item.get("trigger")
                value = item.get("value")
                if not isinstance(trigger, str) or not trigger or not isinstance(value, str) or not value:
                    raise CatalogError(f"{source_path}: entry {entry_order} requires trigger and value")
                connection.execute(
                    "INSERT INTO hotstring_entries "
                    "(profile_id, sort_order, trigger, value, immediate) VALUES (?, ?, ?, ?, ?)",
                    (profile_id, entry_order, trigger, value, int(bool(item.get("immediate")))),
                )
    print(f"Migrated {len(profiles)} hotstring profiles into {DB_PATH}.")


def load_hotstring_profiles() -> list[dict[str, object]]:
    if not DB_PATH.exists():
        raise CatalogError(f"Human catalog not found: {DB_PATH}")
    connection = sqlite3.connect(f"file:{DB_PATH}?mode=ro", uri=True)
    try:
        profiles = connection.execute(
            "SELECT sort_order, id, mode, context_label, platform, active "
            "FROM hotstring_profiles ORDER BY sort_order, id"
        ).fetchall()
        entries = connection.execute(
            "SELECT profile_id, sort_order, trigger, value, immediate "
            "FROM hotstring_entries ORDER BY profile_id, sort_order, trigger"
        ).fetchall()
    finally:
        connection.close()

    by_profile: dict[str, list[dict[str, object]]] = defaultdict(list)
    for profile_id, sort_order, trigger, value, immediate in entries:
        by_profile[str(profile_id)].append({
            "sort_order": sort_order,
            "trigger": trigger,
            "value": value,
            "immediate": bool(immediate),
        })

    result: list[dict[str, object]] = []
    for sort_order, profile_id, mode, context_label, platform, active in profiles:
        try:
            platforms = json.loads(platform)
        except (TypeError, json.JSONDecodeError) as exc:
            raise CatalogError(f"Invalid platform JSON for hotstring profile {profile_id}: {exc}") from exc
        if mode not in {"replace", "sap-command"}:
            raise CatalogError(f"{profile_id}: mode must be replace or sap-command")
        if not isinstance(platforms, list) or not platforms:
            raise CatalogError(f"{profile_id}: platform must be a non-empty JSON array")
        profile_entries = by_profile[str(profile_id)]
        if not profile_entries:
            raise CatalogError(f"{profile_id}: profile must contain at least one entry")
        result.append({
            "sort_order": sort_order,
            "id": profile_id,
            "mode": mode,
            "context_label": context_label,
            "platform": platforms,
            "active": bool(active),
            "entries": profile_entries,
        })
    return result


def load_db() -> list[dict[str, object]]:
    if not DB_PATH.exists():
        raise CatalogError(f"Human catalog not found: {DB_PATH}")
    connection = sqlite3.connect(f"file:{DB_PATH}?mode=ro", uri=True)
    try:
        columns = [row[1] for row in connection.execute("PRAGMA table_info(hotkeys)")]
        if columns != DB_COLUMNS:
            raise CatalogError(f"Unexpected hotkeys schema. Expected columns: {', '.join(DB_COLUMNS)}")
        rows = connection.execute("SELECT * FROM hotkeys ORDER BY sort_order, id").fetchall()
    finally:
        connection.close()
    entries = [_row_to_entry(row) for row in rows]
    validate_entries(entries)
    return entries


def _sap_tcode(entry: dict[str, object]) -> str | None:
    action = str(entry["action"])
    if not action.startswith(SAP_TCODE_ACTION_PREFIX):
        return None
    return action.removeprefix(SAP_TCODE_ACTION_PREFIX)


def validate_entries(entries: list[dict[str, object]]) -> None:
    issues: list[str] = []
    seen_ids: set[str] = set()
    seen_orders: set[int] = set()
    for entry in entries:
        entry_id = str(entry.get("id") or "<missing-id>")
        sort_order = entry.get("sort_order")
        if entry_id in seen_ids:
            issues.append(f"duplicate id: {entry_id}")
        seen_ids.add(entry_id)
        if not isinstance(sort_order, int) or sort_order in seen_orders:
            issues.append(f"{entry_id}: sort_order must be a unique integer")
        if isinstance(sort_order, int):
            seen_orders.add(sort_order)

        file_key = str(entry.get("file") or "")
        if not FILE_KEY_RE.fullmatch(file_key) or ".." in file_key:
            issues.append(f"{entry_id}: invalid file key {file_key!r}")
        entry_type = entry.get("type")
        if entry_type not in {"hotkey", "hotstring"}:
            issues.append(f"{entry_id}: type must be hotkey or hotstring")
        if entry_type == "hotkey" and not entry.get("key"):
            issues.append(f"{entry_id}: hotkey requires key")
        if entry_type == "hotstring" and (not entry.get("trigger") or not entry.get("options")):
            issues.append(f"{entry_id}: hotstring requires trigger and options")
        windows_context = str(entry.get("windows_context") or "").strip()
        if windows_context.startswith("#hotif"):
            issues.append(f"{entry_id}: windows_context must be an expression without #hotif")
        platforms = entry.get("platform")
        if not isinstance(platforms, list) or not platforms:
            issues.append(f"{entry_id}: platform must be a non-empty JSON array")
        elif any(platform not in {"windows", "macos"} for platform in platforms):
            issues.append(f"{entry_id}: platform values must be windows or macos")
        if entry.get("portability") not in {"windows-only", "portable-intent"}:
            issues.append(f"{entry_id}: portability must be windows-only or portable-intent")
        action = str(entry.get("action") or "").strip()
        if not action or not str(entry.get("label") or "").strip():
            issues.append(f"{entry_id}: action and label are required")
        tcode = _sap_tcode(entry)
        if tcode is not None and (
            entry_type != "hotkey" or not SAP_TCODE_RE.fullmatch(tcode)
        ):
            issues.append(
                f"{entry_id}: sap-tcode action requires a hotkey and a valid transaction code"
            )
        if tcode is not None and (
            entry.get("portability") != "portable-intent"
            or set(platforms if isinstance(platforms, list) else []) != {"windows", "macos"}
        ):
            issues.append(
                f"{entry_id}: sap-tcode action requires portable-intent on windows and macos"
            )
    if issues:
        raise CatalogError("Catalog validation failed:\n- " + "\n- ".join(issues))


def _ahk_str(value: str) -> str:
    return value.replace("`", "``").replace('"', '`"')


def _format_hotif(entry: dict[str, object]) -> str | None:
    windows_context = str(entry.get("windows_context") or "").strip()
    return f"#hotif {windows_context}" if windows_context else None


def _render_block(entry: dict[str, object]) -> str:
    action = _sap_tcode(entry)
    rendered_action = (
        f'services.sap.runTcode("{_ahk_str(action)}")'
        if action is not None
        else str(entry["action"])
    )
    if entry["type"] == "hotstring":
        lines = [f'{entry["options"]}{entry["trigger"]}::{{', rendered_action, "}"]
    else:
        lines = [f'{entry["key"]}::{{', rendered_action, "}"]
    return "\n".join(lines)


def generate_file(file_key: str, entries: list[dict[str, object]]) -> str:
    active = [
        entry for entry in entries
        if entry["active"] and "windows" in entry["platform"]
    ]
    lines = [GENERATED_MARKER, "; Human source: platforms/shared/data/hotkeys.db", "; Regenerate: python ai/hotkey_sync.py --sync"]
    if file_key in FILE_HEADERS:
        lines.append(FILE_HEADERS[file_key])
    lines.append("")
    if not active:
        lines.append("; No active entries.")
        return "\n".join(lines) + "\n"

    groups: dict[str, list[dict[str, object]]] = {}
    order: list[str] = []
    for entry in active:
        context_key = str(entry.get("windows_context") or "__global__")
        if context_key not in groups:
            groups[context_key] = []
            order.append(context_key)
        groups[context_key].append(entry)

    previous_hotif: str | None = None
    for context_key in order:
        context_entries = groups[context_key]
        hotif = _format_hotif(context_entries[0])
        if hotif != previous_hotif:
            if hotif:
                lines.append(hotif)
            elif previous_hotif is not None:
                lines.append("#hotif")
            previous_hotif = hotif
        lines.extend(_render_block(entry) for entry in context_entries)
    if previous_hotif is not None:
        lines.append("#hotif")
    return "\n".join(lines) + "\n"


def _display_key(entry: dict[str, object]) -> str:
    if entry["type"] == "hotstring":
        return str(entry["trigger"])
    raw = str(entry["key"])
    prefixes: list[str] = []
    while raw and raw[0] in "~$*":
        raw = raw[1:]
    modifiers = (("#", "Win"), ("^", "Ctrl"), ("!", "Alt"), ("+", "Shift"))
    changed = True
    while changed and raw:
        changed = False
        for symbol, name in modifiers:
            if raw.startswith(symbol):
                prefixes.append(name)
                raw = raw[1:]
                changed = True
                break
    names = {
        "xbutton1": "MouseBack", "xbutton2": "MouseFwd", "pgdn": "PageDown",
        "pgup": "PageUp", "esc": "Esc", "enter": "Enter", "`": "Backtick",
        "left": "Left", "right": "Right", "up": "Up", "down": "Down",
    }
    if raw.lower() in names:
        key_name = names[raw.lower()]
    elif re.fullmatch(r"f\d+", raw.lower()) or (len(raw) == 1 and raw.isalpha()):
        key_name = raw.upper()
    else:
        key_name = raw
    return "+".join([*prefixes, key_name])


def generate_readme(entries: list[dict[str, object]]) -> str:
    active = [entry for entry in entries if entry["active"]]
    hotkey_count = sum(entry["type"] == "hotkey" for entry in active)
    hotstring_count = sum(entry["type"] == "hotstring" for entry in active)
    by_file: dict[str, list[dict[str, object]]] = defaultdict(list)
    for entry in active:
        by_file[str(entry["file"])].append(entry)

    lines = [
        "# Keyflow - Hotkey Reference",
        "",
        "> AUTO-GENERATED by `python ai/hotkey_sync.py --sync` from `platforms/shared/data/hotkeys.db`.",
        "> Humans manage the SQLite database; generated AHK and Markdown files must not be edited directly.",
        "",
        f"Active catalog: **{hotkey_count} hotkeys** and **{hotstring_count} hotstrings**.",
    ]
    ordered_files = sorted(by_file, key=lambda name: (FILE_ORDER.get(name, 999), name))
    for file_key in ordered_files:
        lines.extend(["", f"## {FILE_TITLES.get(file_key, file_key)}", "", "| Trigger | Context | Action | Implementation | Portability |", "|---|---|---|---|---|"])
        for entry in by_file[file_key]:
            trigger = _display_key(entry).replace("|", "\\|")
            context = str(entry.get("context_label") or "global").replace("|", "\\|")
            label = str(entry["label"]).replace("|", "\\|")
            platforms = ", ".join(str(value) for value in entry["platform"])
            portability = str(entry["portability"])
            lines.append(f"| `{trigger}` | {context} | {label} | {platforms} | {portability} |")
    return "\n".join(lines) + "\n"


def _lua_str(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def generate_macos_bindings(entries: list[dict[str, object]]) -> str:
    """Emit binding metadata and portable SAP transaction codes for macOS.
    Other behavior remains hand-authored in actions.lua, matched by id."""
    active = [
        entry for entry in entries
        if entry["active"] and "macos" in entry["platform"]
    ]
    lines = [
        LUA_GENERATED_MARKER,
        "-- Human source: platforms/shared/data/hotkeys.db",
        "-- Regenerate: python ai/hotkey_sync.py --sync",
        "-- Behavior lives in platforms/macos/hammerspoon/actions.lua and hotstrings.lua.",
        "-- sap-tcode:<code> actions expose tcode for the shared SAP adapter.",
        "",
        "return {",
    ]
    for entry in sorted(active, key=lambda e: str(e["id"])):
        key_or_trigger = entry["trigger"] if entry["type"] == "hotstring" else entry["key"]
        tcode = _sap_tcode(entry) or ""
        lines.append(
            "  {"
            f'id = "{_lua_str(str(entry["id"]))}", '
            f'type = "{_lua_str(str(entry["type"]))}", '
            f'key = "{_lua_str(str(key_or_trigger))}", '
            f'contextLabel = "{_lua_str(str(entry.get("context_label") or ""))}", '
            f'tcode = "{_lua_str(tcode)}", '
            f'label = "{_lua_str(str(entry["label"]))}"'
            "},"
        )
    lines.append("}")
    return "\n".join(lines) + "\n"


def generate_windows_hotstring_profile(profile: dict[str, object]) -> str:
    items: list[dict[str, object]] = []
    for entry in profile["entries"]:
        item = {"trigger": entry["trigger"], "value": entry["value"]}
        if entry["immediate"]:
            item["immediate"] = True
        items.append(item)
    payload = {
        "format": "hotstring-items-v1",
        "source": f"shared/hotkeys.db:{profile['id']}",
        "items": items,
    }
    return json.dumps(payload, ensure_ascii=False, indent=2) + "\n"


def generate_macos_hotstring_profiles(profiles: list[dict[str, object]]) -> str:
    lines = [
        LUA_GENERATED_MARKER,
        "-- Human source: platforms/shared/data/hotkeys.db",
        "-- Regenerate: python ai/hotkey_sync.py --sync",
        "",
        "return {",
    ]
    for profile in profiles:
        if not profile["active"] or "macos" not in profile["platform"]:
            continue
        lines.append(
            "  {"
            f'id = "{_lua_str(str(profile["id"]))}", '
            f'mode = "{_lua_str(str(profile["mode"]))}", '
            f'contextLabel = "{_lua_str(str(profile["context_label"]))}", '
            "entries = {"
        )
        for entry in profile["entries"]:
            lines.append(
                "    {"
                f'trigger = "{_lua_str(str(entry["trigger"]))}", '
                f'value = "{_lua_str(str(entry["value"]))}", '
                f'immediate = {"true" if entry["immediate"] else "false"}'
                "},"
            )
        lines.append("  }},")
    lines.extend(["}", ""])
    return "\n".join(lines)


def expected_artifacts(
    entries: list[dict[str, object]],
    profiles: list[dict[str, object]],
) -> dict[Path, str]:
    by_file: dict[str, list[dict[str, object]]] = defaultdict(list)
    for entry in entries:
        by_file[str(entry["file"])].append(entry)
    artifacts = {
        HOTKEYS_DIR / f"{file_key}.ahk": generate_file(file_key, file_entries)
        for file_key, file_entries in by_file.items()
    }
    for profile in profiles:
        artifacts[WINDOWS_DATA_DIR / f"{profile['id']}.json"] = generate_windows_hotstring_profile(profile)
    artifacts[README_PATH] = generate_readme(entries)
    artifacts[MACOS_BINDINGS_PATH] = generate_macos_bindings(entries)
    artifacts[MACOS_HOTSTRING_PROFILES_PATH] = generate_macos_hotstring_profiles(profiles)
    return artifacts


def stale_generated_files(expected_paths: set[Path]) -> list[Path]:
    stale: list[Path] = []
    for path in HOTKEYS_DIR.rglob("*.ahk"):
        if path in expected_paths:
            continue
        try:
            first_line = path.read_text(encoding="utf-8-sig").splitlines()[0]
        except (IndexError, OSError):
            continue
        if first_line == GENERATED_MARKER:
            stale.append(path)
    return stale


def sync(entries: list[dict[str, object]], profiles: list[dict[str, object]]) -> None:
    artifacts = expected_artifacts(entries, profiles)
    for path, content in artifacts.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    stale = stale_generated_files(set(artifacts))
    for path in stale:
        path.unlink()
    print(f"Generated {len(artifacts)} artifacts from {len(entries)} catalog entries.")
    if stale:
        print(f"Removed {len(stale)} stale generated files.")


def check(entries: list[dict[str, object]], profiles: list[dict[str, object]]) -> bool:
    artifacts = expected_artifacts(entries, profiles)
    drift: list[str] = []
    for path, expected in artifacts.items():
        actual = path.read_text(encoding="utf-8-sig") if path.exists() else None
        if actual != expected:
            drift.append(path.relative_to(ROOT).as_posix())
    drift.extend(path.relative_to(ROOT).as_posix() for path in stale_generated_files(set(artifacts)))
    if drift:
        print("Generated hotkey artifacts are stale:")
        for path in sorted(drift):
            print(f"  {path}")
        print("Run: python ai/hotkey_sync.py --sync")
        return False
    print(f"Hotkey catalog is valid and {len(artifacts)} generated artifacts are current.")
    return True


def list_entries(entries: list[dict[str, object]], inactive_only: bool = False) -> None:
    rows = [entry for entry in entries if (not entry["active"]) == inactive_only]
    print(f"{'ID':<30} {'FILE':<22} {'KEY/TRIGGER':<18} {'PLATFORM':<12} {'PORTABILITY':<16} LABEL")
    print("-" * 130)
    for entry in rows:
        platforms = ",".join(str(value) for value in entry["platform"])
        print(f"{entry['id']:<30} {entry['file']:<22} {_display_key(entry):<18} {platforms:<12} {entry['portability']:<16} {entry['label']}")
    print(f"\n{len(rows)} entries")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    actions = parser.add_mutually_exclusive_group(required=True)
    actions.add_argument("--init-db", action="store_true", help="Create a new empty SQLite catalog if none exists.")
    actions.add_argument(
        "--migrate-hotkeys-schema",
        action="store_true",
        help="Migrate the legacy hotkeys table to the current reduced schema.",
    )
    actions.add_argument(
        "--migrate-hotstring-profiles",
        action="store_true",
        help="Import the existing Windows hotstring JSON profiles into hotkeys.db once.",
    )
    actions.add_argument("--sync", action="store_true", help="Generate AHK and Markdown artifacts from hotkeys.db.")
    actions.add_argument("--check", action="store_true", help="Validate the catalog and detect generated artifact drift.")
    actions.add_argument("--list", action="store_true", help="List active catalog entries.")
    actions.add_argument("--list-inactive", action="store_true", help="List inactive catalog entries.")
    args = parser.parse_args()
    try:
        if args.init_db:
            create_db()
            return 0
        if args.migrate_hotkeys_schema:
            migrate_hotkeys_schema()
            return 0
        if args.migrate_hotstring_profiles:
            migrate_hotstring_profiles()
            return 0
        entries = load_db()
        profiles = load_hotstring_profiles()
        if args.sync:
            sync(entries, profiles)
            return 0
        if args.check:
            return 0 if check(entries, profiles) else 1
        list_entries(entries, inactive_only=args.list_inactive)
        return 0
    except (CatalogError, sqlite3.Error, OSError) as exc:
        print(f"hotkey_sync: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    raise SystemExit(main())
