"""
hotkey_sync.py — keyflow hotkey catalog manager

Usage:
  python ai/hotkey_sync.py --init-db        Create/seed hotkeys.db from built-in CATALOG  ← start here
  python ai/hotkey_sync.py --sync           Read hotkeys.db and regenerate all .ahk hotkey files
  python ai/hotkey_sync.py --list           Print all active hotkeys as a table
  python ai/hotkey_sync.py --list-inactive  Print disabled hotkeys
  python ai/hotkey_sync.py --export-json    Export hotkeys.db to hotkeys-catalog.json (read-only snapshot)

Recommended workflow:
  1. python ai/hotkey_sync.py --init-db         (first time only — seeds hotkeys.db from CATALOG)
  2. Open platforms/windows/data/hotkeys.db in DB Browser for SQLite
  3. Delete rows, set active=0, or add rows — just like Excel
  4. python ai/hotkey_sync.py --sync            (regenerates all .ahk files)

Source of truth: hotkeys.db  (edit this)
Generated artifacts: all .ahk files under platforms/windows/hotkeys/
Optional export: hotkeys-catalog.json  (generated by --export-json, not tracked as source)
"""

import json
import os
import sqlite3
import sys
from pathlib import Path
from collections import OrderedDict

ROOT         = Path(__file__).parent.parent
CATALOG_PATH = ROOT / "platforms" / "windows" / "data" / "hotkeys-catalog.json"
DB_PATH      = ROOT / "platforms" / "windows" / "data" / "hotkeys.db"
HOTKEYS_DIR  = ROOT / "platforms" / "windows" / "hotkeys"

DB_SCHEMA = """
CREATE TABLE IF NOT EXISTS hotkeys (
    sort_order    INTEGER,
    id            TEXT PRIMARY KEY,
    file          TEXT NOT NULL,
    type          TEXT NOT NULL,
    key           TEXT,
    trigger       TEXT,
    options       TEXT,
    context       TEXT,
    context_fn    TEXT,
    context_label TEXT,
    track_fn      TEXT,
    track_args    TEXT,
    action        TEXT NOT NULL,
    label         TEXT NOT NULL,
    platform      TEXT NOT NULL,
    active        INTEGER NOT NULL DEFAULT 1,
    notes         TEXT DEFAULT ''
);
"""

# ---------------------------------------------------------------------------
# CATALOG — one dict per hotkey/hotstring.  This is the single source of truth.
# Edit here to add/remove/disable entries, then run --init-catalog and --sync.
#
# Fields:
#   id            — unique snake_case identifier
#   file          — target .ahk file (relative to hotkeys/, without .ahk)
#   type          — "hotkey" | "hotstring"
#   key           — AHK key combo  (hotkeys only)
#   trigger       — trigger text   (hotstrings only)
#   options       — prefix e.g. :*: or ::  (hotstrings only)
#   context       — winactive() argument; null = global (no #HotIf)
#   context_fn    — raw #HotIf expression when not winactive (rare)
#   context_label — human label used as tracking argument
#   track_fn      — tracking function name; null for hotstrings
#   track_args    — list of args for track_fn
#   action        — AHK statement(s) in the hotkey body
#   label         — human description
#   platform      — list: "windows" and/or "macos"
#   active        — False = skip when generating .ahk (easy disable)
#   notes         — optional free text
# ---------------------------------------------------------------------------

W  = ["windows"]
WM = ["windows", "macos"]

def _hk(id_, file_, key, context, context_fn, context_label, track_fn, track_args, action, label, platform=None, active=True, notes=""):
    return {"id": id_, "file": file_, "type": "hotkey", "key": key,
            "trigger": None, "options": None,
            "context": context, "context_fn": context_fn, "context_label": context_label,
            "track_fn": track_fn, "track_args": track_args,
            "action": action, "label": label,
            "platform": platform or W, "active": active, "notes": notes}

def _hs(id_, file_, trigger, options, action, label, platform=None, active=True, notes=""):
    return {"id": id_, "file": file_, "type": "hotstring",
            "key": None, "trigger": trigger, "options": options,
            "context": None, "context_fn": None, "context_label": None,
            "track_fn": None, "track_args": None,
            "action": action, "label": label,
            "platform": platform or W, "active": active, "notes": notes}

def gk(id_, key, action, label, platform=None, active=True, notes=""):
    """Global hotkey shorthand."""
    return _hk(id_, "global", key, None, None, "global",
               "trackHotkeyEvent", [key, "hotkeys/global.ahk", "global"],
               action, label, platform, active, notes)

def ck(id_, file_, key, context, ctx_label, track_fn, action, label, platform=None, active=True, notes="", context_fn=None):
    """Context hotkey shorthand."""
    return _hk(id_, file_, key, context, context_fn, ctx_label,
               track_fn, [key, ctx_label],
               action, label, platform, active, notes)

def ck1(id_, file_, key, context, ctx_label, track_fn, action, label, platform=None, active=True, notes=""):
    """Context hotkey with single-arg tracking (sap-eclipse style)."""
    return _hk(id_, file_, key, context, None, ctx_label,
               track_fn, [key],
               action, label, platform, active, notes)

CATALOG = [
    # ── global: hotstrings ──────────────────────────────────────────────────
    _hs("hs_semicolons",        "global", ";;",  ":*:", 'utilPaste("ñ",,True)',                "Type ñ",                        W),
    _hs("hs_sap_comment_plus",  "global", '"+',  ":*:", "services.sap.insertCommentLine()",    "SAP insert comment line (+)",   W),
    _hs("hs_sap_comment_minus", "global", '"-',  ":*:", "services.sap.insertCommentLine()",    "SAP insert comment line (-)",   W),
    _hs("hs_sap_block_plus",    "global", "*+",  ":*:", "services.sap.insertCommentBlock()",   "SAP insert comment block (+)",  W),
    _hs("hs_sap_block_minus",   "global", "*-",  ":*:", "services.sap.insertCommentBlock()",   "SAP insert comment block (-)",  W),
    _hs("hs_sp",                "global", "sp",  "::",  'utilPaste("summary in prompt",,true)',"Paste 'summary in prompt'",     WM),

    # ── global: hotkeys ─────────────────────────────────────────────────────
    gk("global_alt_e",        "!e",      'services.windowGroup.activateGroup(appActivationTargets,"apps_sap_workspace")', "Activate SAP workspace group"),
    gk("global_alt_a",        "!a",      'services.windowGroup.activateGroup(appActivationTargets,"apps_control")',       "Activate control group"),
    gk("global_alt_s",        "!s",      'services.windowGroup.activateGroup(appActivationTargets,"apps_support")',       "Activate support group"),
    gk("global_alt_d",        "!d",      'services.windowGroup.activateGroup(appActivationTargets,"apps_ide")',           "Activate IDE group"),
    gk("global_alt_f",        "!f",      'services.windowGroup.activateGroup(appActivationTargets,"apps_note")',          "Activate notes group"),
    gk("global_f12",          "f12",     "services.video.control()",                                                      "Video control"),
    gk("global_win_f1",       "#f1",     "services.sap.openPluzDevSession()",                                             "Open SAP Pluz DEV session"),
    gk("global_win_f2",       "#f2",     "services.sap.openPluzQasSession()",                                             "Open SAP Pluz QAS session"),
    gk("global_win_f3",       "#f3",     "services.sap.openPluzPrdSession()",                                             "Open SAP Pluz PRD session"),
    gk("global_win_esc",      "#esc",    "services.windows.resizeHeight()",                                               "Resize window height"),
    gk("global_win_alt_left", "#!left",  "services.windows.snapWindowLeft()",                                             "Snap window left"),
    gk("global_win_alt_right","#!right", "services.windows.snapWindowRight()",                                            "Snap window right"),
    gk("global_win_e",        "#e",      "services.run.openApp(exeXyplorer)",                                             "Open XYplorer"),
    gk("global_win_b",        "#b",      'services.windows.soundToggle("40","90")',                                       "Sound toggle 40% ↔ 90%"),
    gk("global_backslash",    "~\\",     "services.windows.microphoneToggle()",                                           "Microphone toggle"),
    gk("global_ctrl_bslash",  "^\\",     'Send("#!k")',                                                                   "Send Win+Alt+K"),
    gk("global_mouse_fwd",    "xbutton2","services.snipaste.copyPaste(\"{printscreen}\",snipasteTargets)",                 "Snipaste screenshot (PrintScreen)"),
    gk("global_mouse_back",   "xbutton1","services.snipaste.copyPaste(\"^{printscreen}\",snipasteTargets)",               "Snipaste screenshot (Ctrl+PrintScreen)"),
    gk("global_reload",       "$^!+a",   "reload()",                                                                      "Reload AHK script"),
    gk("global_ctrl_c",       "~^c",     "services.snipaste.ctrlC()",                                                     "Snipaste smart copy handler"),

    # ── editors-ide: VS Code / Cursor ───────────────────────────────────────
    ck("vscode_shift_f1", "editors-ide", "+f1",  '"ahk_group group_vscode_editors"', "vscode-group", "trackEditorsHotkeyUsage", 'Send("^+o")',                                         "Go to symbol in workspace"),
    ck("vscode_alt_f1",   "editors-ide", "!f1",  '"ahk_group group_vscode_editors"', "vscode-group", "trackEditorsHotkeyUsage", "services.dynamic.openEditorCommandPaletteWithPercent()", "Command palette with %"),
    ck("vscode_ctrl_f1",  "editors-ide", "^f1",  '"ahk_group group_vscode_editors"', "vscode-group", "trackEditorsHotkeyUsage", 'Send("^+p")',                                         "Command palette"),

    # ── editors-text: Sublime Text ──────────────────────────────────────────
    ck("sublime_alt_left",  "editors-text", "!left",  "exeSublimeText", "sublime", "trackEditorsHotkeyUsage", 'Send("!-")',    "Jump back"),
    ck("sublime_alt_right", "editors-text", "!right", "exeSublimeText", "sublime", "trackEditorsHotkeyUsage", 'Send("!+-")',   "Jump forward"),
    ck("sublime_alt_up",    "editors-text", "!up",    "exeSublimeText", "sublime", "trackEditorsHotkeyUsage", 'Send("^+{up}")', "Select lines up"),
    ck("sublime_alt_down",  "editors-text", "!down",  "exeSublimeText", "sublime", "trackEditorsHotkeyUsage", 'Send("^+{down}")', "Select lines down"),
    ck("sublime_f1",        "editors-text", "f1",     "exeSublimeText", "sublime", "trackEditorsHotkeyUsage", 'Send("^r")',    "Goto anything"),
    ck("sublime_ctrl_f1",   "editors-text", "^f1",    "exeSublimeText", "sublime", "trackEditorsHotkeyUsage", 'Send("^+p")',   "Command palette"),
    ck("sublime_alt_f1",    "editors-text", "!f1",    "exeSublimeText", "sublime", "trackEditorsHotkeyUsage", "services.dynamic.openSublimeCommandPaletteByTag()", "Command palette by tag (#)"),

    # ── editors-text: Notepad++ ─────────────────────────────────────────────
    ck("notepad_alt_left",   "editors-text", "!left",  "exeNotepad", "notepad", "trackEditorsHotkeyUsage", 'Send("^pgdn")',   "Next tab"),
    ck("notepad_alt_right",  "editors-text", "!right", "exeNotepad", "notepad", "trackEditorsHotkeyUsage", 'Send("^pgup")',   "Previous tab"),
    ck("notepad_alt_up",     "editors-text", "!up",    "exeNotepad", "notepad", "trackEditorsHotkeyUsage", 'Send("^+{up}")',  "Move line up"),
    ck("notepad_alt_down",   "editors-text", "!down",  "exeNotepad", "notepad", "trackEditorsHotkeyUsage", 'Send("^+{down}")',"Move line down"),
    ck("notepad_alt_sh_down","editors-text", "!+down", "exeNotepad", "notepad", "trackEditorsHotkeyUsage", 'Send("^d")',      "Duplicate line"),
    ck("notepad_ctrl_sh_k",  "editors-text", "^+k",    "exeNotepad", "notepad", "trackEditorsHotkeyUsage", 'Send("^+l")',     "Select all occurrences"),
    ck("notepad_shift_f1",   "editors-text", "+f1",    "exeNotepad", "notepad", "trackEditorsHotkeyUsage", 'Send("^+!b")',    "Block select mode"),

    # ── editors-text: Obsidian ──────────────────────────────────────────────
    ck("obsidian_f1",       "editors-text", "f1",     "exeObsidian", "obsidian", "trackEditorsHotkeyUsage", 'Send("^o")',      "Quick switcher"),
    ck("obsidian_f5",       "editors-text", "f5",     "exeObsidian", "obsidian", "trackEditorsHotkeyUsage", 'Send("^e")',      "Toggle edit/preview"),
    ck("obsidian_alt_left", "editors-text", "!left",  "exeObsidian", "obsidian", "trackEditorsHotkeyUsage", 'Send("^!{left}")',"Navigate back"),
    ck("obsidian_ctrl_f1",  "editors-text", "^f1",    "exeObsidian", "obsidian", "trackEditorsHotkeyUsage", 'Send("^p")',      "Command palette"),

    # ── editors-office: Word ────────────────────────────────────────────────
    ck("word_alt_6",  "editors-office", "!6",   "exeWinword", "winword", "trackEditorsHotkeyUsage", 'services.snipaste.resizeOffice("60")',   "Snipaste resize image 60%"),
    ck("word_alt_7",  "editors-office", "!7",   "exeWinword", "winword", "trackEditorsHotkeyUsage", 'services.snipaste.resizeOffice("70")',   "Snipaste resize image 70%"),
    ck("word_ctrl_v", "editors-office", "~^v",  "exeWinword", "winword", "trackEditorsHotkeyUsage", "services.snipaste.pasteResizeOffice()",  "Snipaste paste and auto-resize"),

    # ── editors-office: Excel ───────────────────────────────────────────────
    ck("excel_alt_right", "editors-office", "!right", "classExcel", "excel", "trackEditorsHotkeyUsage", 'Send("^pgdn")',    "Next sheet"),
    ck("excel_alt_left",  "editors-office", "!left",  "classExcel", "excel", "trackEditorsHotkeyUsage", 'Send("^pgup")',    "Previous sheet"),
    ck("excel_ctrl_right","editors-office", "^right", "classExcel", "excel", "trackEditorsHotkeyUsage", 'Send("!{right}")', "Navigate right in cell"),
    ck("excel_ctrl_left", "editors-office", "^left",  "classExcel", "excel", "trackEditorsHotkeyUsage", 'Send("!{left}")',  "Navigate left in cell"),

    # ── editors-office: VBA / Visual Basic Editor ───────────────────────────
    ck("vba_f5", "editors-office", "f5", '"Visual Basic"', "visual-basic", "trackEditorsHotkeyUsage", 'Send("{f8}")',     "Step into"),
    ck("vba_f6", "editors-office", "f6", '"Visual Basic"', "visual-basic", "trackEditorsHotkeyUsage", 'Send("+{f8}")',    "Step over"),
    ck("vba_f7", "editors-office", "f7", '"Visual Basic"', "visual-basic", "trackEditorsHotkeyUsage", 'Send("^+{f8}")',   "Step out"),
    ck("vba_f8", "editors-office", "f8", '"Visual Basic"', "visual-basic", "trackEditorsHotkeyUsage", 'Send("{f5}")',     "Run / continue"),

    # ── sap-gui ─────────────────────────────────────────────────────────────
    ck("sap_gui_logon_f1", "sap-gui", "f1", '"Logon for Project"', "sap-gui-project-session", "trackSapGuiHotkeyUsage", "services.sap.reopenSessionFromProjectWindow()", "Reopen session from project window"),
    _hk("sap_gui_ymt_enter","sap-gui","$enter", None,
        'services.sap.isTextInputActive("ahk_group group_sap_runtime_windows")',
        "sap-gui-ymt-input", "trackSapGuiHotkeyUsage", ["$enter", "sap-gui-ymt-input"],
        "services.sap.runTcodeFromFocusedInput()", "YMT run tcode from focused input", W, True,
        "Preceded by #hotif winactive(\"YMT\") in original file (non-stacking in AHK v2)"),
    ck("sap_gui_alt_left",  "sap-gui", "!left",  '"ahk_group group_sap_runtime_windows"', "sap-gui-session", "trackSapGuiHotkeyUsage", 'Send("+{f6}")',                    "Navigate back"),
    ck("sap_gui_alt_right", "sap-gui", "!right", '"ahk_group group_sap_runtime_windows"', "sap-gui-session", "trackSapGuiHotkeyUsage", 'Send("+{f7}")',                    "Navigate forward"),
    ck("sap_gui_alt_up",    "sap-gui", "!up",    '"ahk_group group_sap_runtime_windows"', "sap-gui-session", "trackSapGuiHotkeyUsage", 'Send("^!{up}")',                   "Move item up"),
    ck("sap_gui_alt_down",  "sap-gui", "!down",  '"ahk_group group_sap_runtime_windows"', "sap-gui-session", "trackSapGuiHotkeyUsage", 'Send("^!{down}")',                 "Move item down"),
    ck("sap_gui_alt_sh_dn", "sap-gui", "!+down", '"ahk_group group_sap_runtime_windows"', "sap-gui-session", "trackSapGuiHotkeyUsage", 'Send("^d")',                       "Duplicate line/row"),
    ck("sap_gui_ctrl_g",    "sap-gui", "^g",     '"ahk_group group_sap_runtime_windows"', "sap-gui-session", "trackSapGuiHotkeyUsage", 'Send("^o")',                       "Open object"),
    ck("sap_gui_ctrl_sh_w", "sap-gui", "^+w",    '"ahk_group group_sap_runtime_windows"', "sap-gui-session", "trackSapGuiHotkeyUsage", "services.sap.exitSession()",       "Exit session"),
    ck("sap_gui_ctrl_sh_k", "sap-gui", "^+k",    '"ahk_group group_sap_runtime_windows"', "sap-gui-session", "trackSapGuiHotkeyUsage", 'Send("^+l")',                      "Select all occurrences"),
    ck("sap_gui_ctrl_d",    "sap-gui", "^d",     '"ahk_group group_sap_runtime_windows"', "sap-gui-session", "trackSapGuiHotkeyUsage", "services.sap.toggleDebugMode()",   "Toggle debug mode"),
    ck("sap_gui_ctrl_b",    "sap-gui", "^b",     '"ahk_group group_sap_runtime_windows"', "sap-gui-session", "trackSapGuiHotkeyUsage", "services.sap.focusGuiWindows()",   "Focus SAP GUI windows"),
    ck("sap_gui_alt_5",     "sap-gui", "!5",     '"ahk_group group_sap_runtime_windows"', "sap-gui-session", "trackSapGuiHotkeyUsage", "services.sap.openWorkbenchOptions()","Workbench options"),
    ck("sap_gui_alt_6",     "sap-gui", "!6",     '"ahk_group group_sap_runtime_windows"', "sap-gui-session", "trackSapGuiHotkeyUsage", "services.sap.openSe16n()",          "SE16N table browser"),
    ck("sap_gui_alt_7",     "sap-gui", "!7",     '"ahk_group group_sap_runtime_windows"', "sap-gui-session", "trackSapGuiHotkeyUsage", "services.sap.openSe37()",           "SE37 function modules"),
    ck("sap_gui_alt_8",     "sap-gui", "!8",     '"ahk_group group_sap_runtime_windows"', "sap-gui-session", "trackSapGuiHotkeyUsage", "services.sap.openSe38()",           "SE38 ABAP editor"),
    ck("sap_gui_alt_9",     "sap-gui", "!9",     '"ahk_group group_sap_runtime_windows"', "sap-gui-session", "trackSapGuiHotkeyUsage", "services.sap.openSe09()",           "SE09 transport organizer"),
    ck("sap_gui_alt_0",     "sap-gui", "!0",     '"ahk_group group_sap_runtime_windows"', "sap-gui-session", "trackSapGuiHotkeyUsage", "services.sap.openSe80()",           "SE80 object navigator"),

    # ── sap-eclipse ─────────────────────────────────────────────────────────
    ck1("eclipse_alt_pgdn",  "sap-eclipse", "!pgdn",  "exeEclipse", "sap-eclipse", "trackSapEclipseHotkeyUsage", 'Send("^pgdn")',                                  "Next editor tab"),
    ck1("eclipse_alt_pgup",  "sap-eclipse", "!pgup",  "exeEclipse", "sap-eclipse", "trackSapEclipseHotkeyUsage", 'Send("^pgup")',                                  "Previous editor tab"),
    ck1("eclipse_alt_sh_dn", "sap-eclipse", "!+down", "exeEclipse", "sap-eclipse", "trackSapEclipseHotkeyUsage", 'Send("^!down")',                                 "Move line down"),
    ck1("eclipse_ctrl_g",    "sap-eclipse", "^g",     "exeEclipse", "sap-eclipse", "trackSapEclipseHotkeyUsage", 'Send("^1")',                                     "Quick fix"),
    ck1("eclipse_backtick",  "sap-eclipse", "`",      "exeEclipse", "sap-eclipse", "trackSapEclipseHotkeyUsage", "services.sap.promptAndOpenAbapObject()",         "Prompt and open ABAP object",    W, True, "", ),
    ck1("eclipse_ctrl_slash","sap-eclipse", "^/",     "exeEclipse", "sap-eclipse", "trackSapEclipseHotkeyUsage", 'Send("^7")',                                     "Toggle comment"),
    ck1("eclipse_ctrl_sh_k", "sap-eclipse", "^+k",    "exeEclipse", "sap-eclipse", "trackSapEclipseHotkeyUsage", 'Send("^d")',                                     "Delete line"),
    ck1("eclipse_f1",        "sap-eclipse", "f1",     "exeEclipse", "sap-eclipse", "trackSapEclipseHotkeyUsage", "services.sap.promptAndSearchAbapObject()",       "Search ABAP object"),
    ck1("eclipse_alt_f1",    "sap-eclipse", "!f1",    "exeEclipse", "sap-eclipse", "trackSapEclipseHotkeyUsage", 'Send("^+a")',                                    "Open type"),
    ck1("eclipse_f2",        "sap-eclipse", "f2",     "exeEclipse", "sap-eclipse", "trackSapEclipseHotkeyUsage", 'Send("!+r")',                                    "Rename"),
    ck1("eclipse_shift_f2",  "sap-eclipse", "+f2",    "exeEclipse", "sap-eclipse", "trackSapEclipseHotkeyUsage", 'Send("{f2}")',                                   "Inline rename"),
    ck1("eclipse_alt_f2",    "sap-eclipse", "!f2",    "exeEclipse", "sap-eclipse", "trackSapEclipseHotkeyUsage", 'Send("!{f2}")',                                  "Alt+F2"),
    ck1("eclipse_ctrl_sh_f2","sap-eclipse", "^+f2",   "exeEclipse", "sap-eclipse", "trackSapEclipseHotkeyUsage", 'Send("^+{f2}")',                                 "Ctrl+Shift+F2"),
    ck1("eclipse_ctrl_n",    "sap-eclipse", "^n",     "exeEclipse", "sap-eclipse", "trackSapEclipseHotkeyUsage", 'Send("!{f8}")',                                  "Run with variant"),
    ck1("eclipse_ctrl_sh_b", "sap-eclipse", "^+b",    "exeEclipse", "sap-eclipse", "trackSapEclipseHotkeyUsage", "services.sap.focusEclipseWindows()",             "Focus Eclipse windows"),
    ck1("eclipse_ctrl_5",    "sap-eclipse", "^5",     "exeEclipse", "sap-eclipse", "trackSapEclipseHotkeyUsage", "services.sap.startQuickDebug()",                 "Start quick debug"),
    ck1("eclipse_alt_j",     "sap-eclipse", "!j",     "exeEclipse", "sap-eclipse", "trackSapEclipseHotkeyUsage", 'Send("{down}")',                                 "Down arrow"),
    ck1("eclipse_alt_k",     "sap-eclipse", "!k",     "exeEclipse", "sap-eclipse", "trackSapEclipseHotkeyUsage", 'Send("{up}")',                                   "Up arrow"),
    ck1("eclipse_alt_i",     "sap-eclipse", "!i",     "exeEclipse", "sap-eclipse", "trackSapEclipseHotkeyUsage", 'Send("^!i")',                                    "Format/indent"),
    ck1("eclipse_ctrl_s",    "sap-eclipse", "^s",     "exeEclipse", "sap-eclipse", "trackSapEclipseHotkeyUsage", "services.sap.saveCodeArtifact()",                "Save code artifact"),
    ck("eclipse_db_alt_up",  "sap-eclipse", "!up",    '"- DATABASE TABLE"', "sap-eclipse-database-table", "trackSapEclipseHotkeyUsage", 'Send("!{up}")',           "Move field up"),
    ck("eclipse_db_alt_dn",  "sap-eclipse", "!down",  '"- DATABASE TABLE"', "sap-eclipse-database-table", "trackSapEclipseHotkeyUsage", 'Send("!{down}")',         "Move field down"),

    # ── domains/comms: Teams ─────────────────────────────────────────────────
    ck("teams_f1",   "domains/comms", "f1",  "exeMsTeams", "teams", "trackDomainsHotkeyUsage", "services.dynamic.openTeamsSearchAndGoToField()", "Open search and go to field"),
    ck("teams_alt_2","domains/comms", "!2",  "exeMsTeams", "teams", "trackDomainsHotkeyUsage", 'Send("^2")',                                     "Activity tab"),
    ck("teams_alt_3","domains/comms", "!3",  "exeMsTeams", "teams", "trackDomainsHotkeyUsage", 'Send("^3")',                                     "Chat tab"),

    # ── domains/comms: WhatsApp ──────────────────────────────────────────────
    ck("whatsapp_f1",      "domains/comms", "f1",  "titleWhatsapp", "whatsapp", "trackDomainsHotkeyUsage", "services.whatsapp.archive()",      "Archive chat"),
    ck("whatsapp_f2",      "domains/comms", "f2",  "titleWhatsapp", "whatsapp", "trackDomainsHotkeyUsage", "services.whatsapp.delete()",       "Delete chat"),
    ck("whatsapp_shift_f1","domains/comms", "+f1", "titleWhatsapp", "whatsapp", "trackDomainsHotkeyUsage", "services.whatsapp.clearArchive()", "Clear archive"),

    # ── domains/comms: Outlook ───────────────────────────────────────────────
    ck("outlook_alt_1","domains/comms", "!1", "exeOutlook", "outlook", "trackDomainsHotkeyUsage", 'Send("^{f2}")', "Shortcut 1"),
    ck("outlook_alt_2","domains/comms", "!2", "exeOutlook", "outlook", "trackDomainsHotkeyUsage", 'Send("^{f3}")', "Shortcut 2"),
    ck("outlook_alt_3","domains/comms", "!3", "exeOutlook", "outlook", "trackDomainsHotkeyUsage", 'Send("^{f4}")', "Shortcut 3"),
    ck("outlook_alt_4","domains/comms", "!4", "exeOutlook", "outlook", "trackDomainsHotkeyUsage", 'Send("^{f5}")', "Shortcut 4"),
    ck("outlook_alt_5","domains/comms", "!5", "exeOutlook", "outlook", "trackDomainsHotkeyUsage", 'Send("^{f6}")', "Shortcut 5"),

    # ── domains/media-web: VLC ───────────────────────────────────────────────
    ck("vlc_d", "domains/media-web", "d", "exeVlc", "vlc", "trackDomainsHotkeyUsage", 'Send("]")', "Speed up playback"),
    ck("vlc_s", "domains/media-web", "s", "exeVlc", "vlc", "trackDomainsHotkeyUsage", 'Send("[")', "Slow down playback"),

    # ── domains/media-web: Firefox ───────────────────────────────────────────
    ck("firefox_ctrl_sh_n", "domains/media-web", "^+n", "exeFirefox", "firefox", "trackDomainsHotkeyUsage", 'Send("^+p")', "Open private window"),

    # ── domains/productivity: Snipaste ───────────────────────────────────────
    ck("snipaste_enter", "domains/productivity", "~enter", "titleSnipaste", "snipaste", "trackDomainsHotkeyUsage", 'services.snipaste.copyPaste("",snipasteTargets)', "Copy + paste to targets"),

    # ── domains/productivity: Launcher ───────────────────────────────────────
    ck("launcher_f12",   "domains/productivity", "f12", '"ahk_group group_launcher"', "launcher", "trackDomainsHotkeyUsage", "services.launcher.pasteSelectedFiles()",          "Paste selected files"),
    ck("launcher_ctrl_s","domains/productivity", "^s",  '"ahk_group group_launcher"', "launcher", "trackDomainsHotkeyUsage", "services.launcher.saveClipboardToSelectedFile()", "Save clipboard to selected file"),
    ck("launcher_alt_p", "domains/productivity", "!p",  '"ahk_group group_launcher"', "launcher", "trackDomainsHotkeyUsage", "services.launcher.openSelectedMedia()",           "Open selected media"),

    # ── domains/productivity: XYplorer ───────────────────────────────────────
    ck("xyplorer_f5", "domains/productivity", "f5", "exeXyplorer", "xyplorer", "trackDomainsHotkeyUsage", "services.dynamic.refreshAndCloseXyplorerTab()", "Refresh and close current tab"),

    # ── domains/productivity: Task Time Tracker ──────────────────────────────
    ck("time_tracker_f1", "domains/productivity", "f1", "titleTaskTimeTracker", "task-time-tracker", "trackDomainsHotkeyUsage", "services.dynamic.copyAndRefreshAppTime()", "Copy time and refresh"),
]

# ---------------------------------------------------------------------------
# FILE HEADERS — per-file comment inserted at the top of each generated .ahk
# ---------------------------------------------------------------------------
FILE_HEADERS = {
    "sap-gui":     "; SAP GUI: solo disparadores hacia services.sap.*; la logica vive en library/automation/sap.ahk.",
    "sap-eclipse": "; SAP ADT/Eclipse: solo disparadores hacia services.sap.*; la logica vive en library/automation/sap.ahk.",
}

# ---------------------------------------------------------------------------
# GENERATOR
# ---------------------------------------------------------------------------

def _fmt_track(entry):
    args = entry["track_args"]
    quoted = ", ".join(f'"{a}"' for a in args)
    return f'{entry["track_fn"]}({quoted})'

def _fmt_hotif(entry):
    if entry.get("context_fn"):
        return f'#hotif {entry["context_fn"]}'
    if entry["context"]:
        return f'#hotif winactive({entry["context"]})'
    return None

def _render_block(entry):
    lines = []
    if entry["type"] == "hotstring":
        lines.append(f'{entry["options"]}{entry["trigger"]}::{{')
        lines.append(entry["action"])
        lines.append("}")
    else:
        lines.append(f'{entry["key"]}::{{')
        if entry["track_fn"]:
            lines.append(_fmt_track(entry))
        lines.append(entry["action"])
        lines.append("}")
    return "\n".join(lines)

def generate_file(file_key, entries):
    """Generate AHK content for one hotkey file."""
    active = [e for e in entries if e["active"]]
    if not active:
        return ""

    lines = ["; AUTO-GENERATED by ai/hotkey_sync.py"]
    lines.append("; Edit platforms/windows/data/hotkeys-catalog.json, then run: python ai/hotkey_sync.py --sync")
    if file_key in FILE_HEADERS:
        lines.append(FILE_HEADERS[file_key])
    lines.append("")

    # Group entries preserving catalog order, by (context_fn or context or "__global__")
    seen_contexts = []
    groups = {}
    for e in active:
        key = e.get("context_fn") or e.get("context") or "__global__"
        if key not in groups:
            groups[key] = []
            seen_contexts.append(key)
        groups[key].append(e)

    prev_context = None
    for ctx_key in seen_contexts:
        ctx_entries = groups[ctx_key]
        sample = ctx_entries[0]
        new_hotif = _fmt_hotif(sample)

        if new_hotif != prev_context:
            if new_hotif:
                lines.append(new_hotif)
            elif prev_context is not None:
                lines.append("#hotif")
            prev_context = new_hotif

        for e in ctx_entries:
            lines.append(_render_block(e))

    # Close final context
    if prev_context is not None:
        lines.append("#hotif")

    return "\n".join(lines) + "\n"

def sync(catalog_entries):
    """Regenerate all .ahk hotkey files from catalog."""
    by_file = {}
    for e in catalog_entries:
        f = e["file"]
        by_file.setdefault(f, []).append(e)

    written = []
    for file_key, entries in by_file.items():
        path = HOTKEYS_DIR / (file_key + ".ahk")
        path.parent.mkdir(parents=True, exist_ok=True)
        content = generate_file(file_key, entries)
        path.write_text(content, encoding="utf-8")
        written.append(str(path))
    return written

def export_json():
    """Export current hotkeys.db to hotkeys-catalog.json (read-only snapshot for AI/review)."""
    entries = load_db() if DB_PATH.exists() else CATALOG
    doc = {
        "description": "Read-only export from hotkeys.db. Do NOT edit this file — edit hotkeys.db instead, then run: python ai/hotkey_sync.py --sync",
        "generated_by": "python ai/hotkey_sync.py --export-json",
        "version": "1.0.0",
        "hotkeys": entries
    }
    CATALOG_PATH.write_text(json.dumps(doc, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"Exported {len(entries)} entries → {CATALOG_PATH}")

# ---------------------------------------------------------------------------
# SQLITE
# ---------------------------------------------------------------------------

def _entry_to_row(i, e):
    return (
        i,
        e["id"], e["file"], e["type"],
        e.get("key"), e.get("trigger"), e.get("options"),
        e.get("context"), e.get("context_fn"), e.get("context_label"),
        e.get("track_fn"),
        json.dumps(e["track_args"], ensure_ascii=False) if e.get("track_args") is not None else None,
        e["action"], e["label"],
        json.dumps(e["platform"], ensure_ascii=False),
        1 if e.get("active", True) else 0,
        e.get("notes", ""),
    )

def _row_to_entry(row):
    cols = ["sort_order","id","file","type","key","trigger","options","context","context_fn",
            "context_label","track_fn","track_args","action","label","platform","active","notes"]
    d = dict(zip(cols, row))
    d["track_args"] = json.loads(d["track_args"]) if d["track_args"] else None
    d["platform"]   = json.loads(d["platform"])
    d["active"]     = bool(d["active"])
    del d["sort_order"]
    return d

def init_db(source=None):
    """Create/seed hotkeys.db from CATALOG (or supplied list)."""
    entries = source or CATALOG
    con = sqlite3.connect(DB_PATH)
    con.executescript(DB_SCHEMA)
    con.execute("DELETE FROM hotkeys")
    con.executemany(
        "INSERT INTO hotkeys VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
        [_entry_to_row(i, e) for i, e in enumerate(entries)]
    )
    con.commit()
    con.close()
    print(f"Seeded {len(entries)} rows → {DB_PATH}")
    print(f"Open in DB Browser for SQLite: https://sqlitebrowser.org/dl/")

def load_db():
    """Load all rows from hotkeys.db ordered by sort_order."""
    con = sqlite3.connect(DB_PATH)
    rows = con.execute("SELECT * FROM hotkeys ORDER BY sort_order").fetchall()
    con.close()
    return [_row_to_entry(r) for r in rows]

def list_hotkeys(entries, inactive_only=False):
    rows = [e for e in entries if (not e["active"]) == inactive_only]
    print(f"{'ID':<30} {'FILE':<22} {'KEY/TRIGGER':<14} {'PLATFORM':<18} {'LABEL'}")
    print("-" * 110)
    for e in rows:
        key = e.get("key") or e.get("trigger") or ""
        plat = ",".join(e.get("platform") or [])
        print(f"{e['id']:<30} {e['file']:<22} {key:<14} {plat:<18} {e['label']}")
    print(f"\n{len(rows)} entries")

def _best_source(label=""):
    """Return entries from hotkeys.db, falling back to in-memory CATALOG."""
    if DB_PATH.exists():
        entries = load_db()
        src = f"hotkeys.db ({len(entries)} rows)"
    else:
        entries = CATALOG
        src = f"in-memory CATALOG ({len(entries)} entries) — run --init-db to create hotkeys.db"
    if label:
        print(f"Source: {src}")
    return entries

# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    # Ensure Unicode output works on Windows terminals
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    args = sys.argv[1:]
    if "--init-db" in args:
        init_db()
    elif "--export-json" in args:
        export_json()
    elif "--sync" in args:
        entries = _best_source(label="sync")
        written = sync(entries)
        print(f"Regenerated {len(written)} file(s):")
        for w in written:
            print(f"  {w}")
    elif "--list" in args:
        list_hotkeys(_best_source(), inactive_only=False)
    elif "--list-inactive" in args:
        list_hotkeys(_best_source(), inactive_only=True)
    else:
        print(__doc__)
