"""Manage generated hotkey artifacts from the human-owned SQLite catalog.

Human workflow:
  1. Edit platforms/windows/data/hotkeys.db with a SQLite editor.
  2. Run: python ai/hotkey_sync.py --sync

AI/reviewer workflow:
  python ai/hotkey_sync.py --check
  python ai/hotkey_sync.py --list

Source of truth: platforms/windows/data/hotkeys.db
Generated artifacts: platforms/windows/hotkeys/*.ahk and hotkeys/README.md
"""

from __future__ import annotations

import argparse
import json
import re
import sqlite3
import sys
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).parent.parent
DB_PATH = ROOT / "platforms" / "windows" / "data" / "hotkeys.db"
HOTKEYS_DIR = ROOT / "platforms" / "windows" / "hotkeys"
README_PATH = HOTKEYS_DIR / "README.md"
GENERATED_MARKER = "; AUTO-GENERATED by ai/hotkey_sync.py"

DB_SCHEMA = """
CREATE TABLE IF NOT EXISTS hotkeys (
    sort_order    INTEGER,
    id            TEXT PRIMARY KEY,
    file          TEXT NOT NULL,
    type          TEXT NOT NULL,
    key           TEXT,
    trigger       TEXT,
    options       TEXT,
    context       TEXT,
    context_fn    TEXT,
    context_label TEXT,
    track_fn      TEXT,
    track_args    TEXT,
    action        TEXT NOT NULL,
    label         TEXT NOT NULL,
    platform      TEXT NOT NULL,
    active        INTEGER NOT NULL DEFAULT 1,
    notes         TEXT DEFAULT '',
    portability   TEXT NOT NULL DEFAULT 'windows-only'
);
"""

DB_COLUMNS = [
    "sort_order", "id", "file", "type", "key", "trigger", "options",
    "context", "context_fn", "context_label", "track_fn", "track_args",
    "action", "label", "platform", "active", "notes", "portability",
]

FILE_HEADERS = {
    "sap-gui": "; SAP GUI triggers only; implementation lives in library/automation/sap.ahk.",
    "sap-eclipse": "; SAP ADT/Eclipse triggers only; implementation lives in library/automation/sap.ahk.",
}

FILE_TITLES = {
    "global": "Global",
    "sap-gui": "SAP GUI and NWBC",
    "sap-eclipse": "SAP Eclipse / ADT",
    "domains/productivity": "Productivity workflows",
}

FILE_ORDER = {name: i for i, name in enumerate(FILE_TITLES)}
FILE_KEY_RE = re.compile(r"^[a-z0-9][a-z0-9/-]*$")


class CatalogError(RuntimeError):
    pass


def _row_to_entry(row: tuple[object, ...]) -> dict[str, object]:
    entry = dict(zip(DB_COLUMNS, row))
    try:
        entry["track_args"] = json.loads(entry["track_args"]) if entry["track_args"] else None
        entry["platform"] = json.loads(entry["platform"])
    except (TypeError, json.JSONDecodeError) as exc:
        raise CatalogError(f"Invalid JSON fields for hotkey {entry.get('id')}: {exc}") from exc
    entry["active"] = bool(entry["active"])
    return entry


def create_db() -> None:
    if DB_PATH.exists():
        raise CatalogError(f"Refusing to replace existing human catalog: {DB_PATH}")
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    with sqlite3.connect(DB_PATH) as connection:
        connection.executescript(DB_SCHEMA)
    print(f"Created empty catalog: {DB_PATH}")


def load_db() -> list[dict[str, object]]:
    if not DB_PATH.exists():
        raise CatalogError(f"Human catalog not found: {DB_PATH}")
    connection = sqlite3.connect(f"file:{DB_PATH}?mode=ro", uri=True)
    try:
        columns = [row[1] for row in connection.execute("PRAGMA table_info(hotkeys)")]
        if columns != DB_COLUMNS:
            raise CatalogError(f"Unexpected hotkeys schema. Expected columns: {', '.join(DB_COLUMNS)}")
        rows = connection.execute("SELECT * FROM hotkeys ORDER BY sort_order, id").fetchall()
    finally:
        connection.close()
    entries = [_row_to_entry(row) for row in rows]
    validate_entries(entries)
    return entries


def validate_entries(entries: list[dict[str, object]]) -> None:
    issues: list[str] = []
    seen_ids: set[str] = set()
    seen_orders: set[int] = set()
    for entry in entries:
        entry_id = str(entry.get("id") or "<missing-id>")
        sort_order = entry.get("sort_order")
        if entry_id in seen_ids:
            issues.append(f"duplicate id: {entry_id}")
        seen_ids.add(entry_id)
        if not isinstance(sort_order, int) or sort_order in seen_orders:
            issues.append(f"{entry_id}: sort_order must be a unique integer")
        if isinstance(sort_order, int):
            seen_orders.add(sort_order)

        file_key = str(entry.get("file") or "")
        if not FILE_KEY_RE.fullmatch(file_key) or ".." in file_key:
            issues.append(f"{entry_id}: invalid file key {file_key!r}")
        entry_type = entry.get("type")
        if entry_type not in {"hotkey", "hotstring"}:
            issues.append(f"{entry_id}: type must be hotkey or hotstring")
        if entry_type == "hotkey" and not entry.get("key"):
            issues.append(f"{entry_id}: hotkey requires key")
        if entry_type == "hotstring" and (not entry.get("trigger") or not entry.get("options")):
            issues.append(f"{entry_id}: hotstring requires trigger and options")
        if entry.get("context") and entry.get("context_fn"):
            issues.append(f"{entry_id}: context and context_fn are mutually exclusive")
        if entry.get("track_fn") and not isinstance(entry.get("track_args"), list):
            issues.append(f"{entry_id}: tracked hotkey requires JSON array track_args")
        platforms = entry.get("platform")
        if not isinstance(platforms, list) or not platforms:
            issues.append(f"{entry_id}: platform must be a non-empty JSON array")
        if entry.get("portability") not in {"windows-only", "portable-intent"}:
            issues.append(f"{entry_id}: portability must be windows-only or portable-intent")
        if not str(entry.get("action") or "").strip() or not str(entry.get("label") or "").strip():
            issues.append(f"{entry_id}: action and label are required")
    if issues:
        raise CatalogError("Catalog validation failed:\n- " + "\n- ".join(issues))


def _ahk_str(value: str) -> str:
    return value.replace("`", "``").replace('"', '`"')


def _format_track(entry: dict[str, object]) -> str:
    args = entry["track_args"] or []
    quoted = ", ".join(f'"{_ahk_str(str(arg))}"' for arg in args)
    return f'{entry["track_fn"]}({quoted})'


def _format_hotif(entry: dict[str, object]) -> str | None:
    if entry.get("context_fn"):
        return f'#hotif {entry["context_fn"]}'
    if entry.get("context"):
        return f'#hotif winactive({entry["context"]})'
    return None


def _render_block(entry: dict[str, object]) -> str:
    if entry["type"] == "hotstring":
        lines = [f'{entry["options"]}{entry["trigger"]}::{{', str(entry["action"]), "}"]
    else:
        lines = [f'{entry["key"]}::{{']
        if entry.get("track_fn"):
            lines.append(_format_track(entry))
        lines.extend([str(entry["action"]), "}"])
    return "\n".join(lines)


def generate_file(file_key: str, entries: list[dict[str, object]]) -> str:
    active = [entry for entry in entries if entry["active"]]
    lines = [GENERATED_MARKER, "; Human source: platforms/windows/data/hotkeys.db", "; Regenerate: python ai/hotkey_sync.py --sync"]
    if file_key in FILE_HEADERS:
        lines.append(FILE_HEADERS[file_key])
    lines.append("")
    if not active:
        lines.append("; No active entries.")
        return "\n".join(lines) + "\n"

    groups: dict[str, list[dict[str, object]]] = {}
    order: list[str] = []
    for entry in active:
        context_key = str(entry.get("context_fn") or entry.get("context") or "__global__")
        if context_key not in groups:
            groups[context_key] = []
            order.append(context_key)
        groups[context_key].append(entry)

    previous_hotif: str | None = None
    for context_key in order:
        context_entries = groups[context_key]
        hotif = _format_hotif(context_entries[0])
        if hotif != previous_hotif:
            if hotif:
                lines.append(hotif)
            elif previous_hotif is not None:
                lines.append("#hotif")
            previous_hotif = hotif
        lines.extend(_render_block(entry) for entry in context_entries)
    if previous_hotif is not None:
        lines.append("#hotif")
    return "\n".join(lines) + "\n"


def _display_key(entry: dict[str, object]) -> str:
    if entry["type"] == "hotstring":
        return str(entry["trigger"])
    raw = str(entry["key"])
    prefixes: list[str] = []
    while raw and raw[0] in "~$*":
        raw = raw[1:]
    modifiers = (("#", "Win"), ("^", "Ctrl"), ("!", "Alt"), ("+", "Shift"))
    changed = True
    while changed and raw:
        changed = False
        for symbol, name in modifiers:
            if raw.startswith(symbol):
                prefixes.append(name)
                raw = raw[1:]
                changed = True
                break
    names = {
        "xbutton1": "MouseBack", "xbutton2": "MouseFwd", "pgdn": "PageDown",
        "pgup": "PageUp", "esc": "Esc", "enter": "Enter", "`": "Backtick",
        "left": "Left", "right": "Right", "up": "Up", "down": "Down",
    }
    if raw.lower() in names:
        key_name = names[raw.lower()]
    elif re.fullmatch(r"f\d+", raw.lower()) or (len(raw) == 1 and raw.isalpha()):
        key_name = raw.upper()
    else:
        key_name = raw
    return "+".join([*prefixes, key_name])


def generate_readme(entries: list[dict[str, object]]) -> str:
    active = [entry for entry in entries if entry["active"]]
    hotkey_count = sum(entry["type"] == "hotkey" for entry in active)
    hotstring_count = sum(entry["type"] == "hotstring" for entry in active)
    by_file: dict[str, list[dict[str, object]]] = defaultdict(list)
    for entry in active:
        by_file[str(entry["file"])].append(entry)

    lines = [
        "# Keyflow - Hotkey Reference",
        "",
        "> AUTO-GENERATED by `python ai/hotkey_sync.py --sync` from `platforms/windows/data/hotkeys.db`.",
        "> Humans manage the SQLite database; generated AHK and Markdown files must not be edited directly.",
        "",
        f"Active catalog: **{hotkey_count} hotkeys** and **{hotstring_count} hotstrings**.",
    ]
    ordered_files = sorted(by_file, key=lambda name: (FILE_ORDER.get(name, 999), name))
    for file_key in ordered_files:
        lines.extend(["", f"## {FILE_TITLES.get(file_key, file_key)}", "", "| Trigger | Context | Action | Implementation | Portability |", "|---|---|---|---|---|"])
        for entry in by_file[file_key]:
            trigger = _display_key(entry).replace("|", "\\|")
            context = str(entry.get("context_label") or "global").replace("|", "\\|")
            label = str(entry["label"]).replace("|", "\\|")
            platforms = ", ".join(str(value) for value in entry["platform"])
            portability = str(entry["portability"])
            lines.append(f"| `{trigger}` | {context} | {label} | {platforms} | {portability} |")
    return "\n".join(lines) + "\n"


def expected_artifacts(entries: list[dict[str, object]]) -> dict[Path, str]:
    by_file: dict[str, list[dict[str, object]]] = defaultdict(list)
    for entry in entries:
        by_file[str(entry["file"])].append(entry)
    artifacts = {HOTKEYS_DIR / f"{file_key}.ahk": generate_file(file_key, file_entries) for file_key, file_entries in by_file.items()}
    artifacts[README_PATH] = generate_readme(entries)
    return artifacts


def stale_generated_files(expected_paths: set[Path]) -> list[Path]:
    stale: list[Path] = []
    for path in HOTKEYS_DIR.rglob("*.ahk"):
        if path in expected_paths or path.name == "hotkey-tracking.ahk":
            continue
        try:
            first_line = path.read_text(encoding="utf-8-sig").splitlines()[0]
        except (IndexError, OSError):
            continue
        if first_line == GENERATED_MARKER:
            stale.append(path)
    return stale


def sync(entries: list[dict[str, object]]) -> None:
    artifacts = expected_artifacts(entries)
    for path, content in artifacts.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    stale = stale_generated_files(set(artifacts))
    for path in stale:
        path.unlink()
    print(f"Generated {len(artifacts)} artifacts from {len(entries)} catalog entries.")
    if stale:
        print(f"Removed {len(stale)} stale generated files.")


def check(entries: list[dict[str, object]]) -> bool:
    artifacts = expected_artifacts(entries)
    drift: list[str] = []
    for path, expected in artifacts.items():
        actual = path.read_text(encoding="utf-8-sig") if path.exists() else None
        if actual != expected:
            drift.append(path.relative_to(ROOT).as_posix())
    drift.extend(path.relative_to(ROOT).as_posix() for path in stale_generated_files(set(artifacts)))
    if drift:
        print("Generated hotkey artifacts are stale:")
        for path in sorted(drift):
            print(f"  {path}")
        print("Run: python ai/hotkey_sync.py --sync")
        return False
    print(f"Hotkey catalog is valid and {len(artifacts)} generated artifacts are current.")
    return True


def list_entries(entries: list[dict[str, object]], inactive_only: bool = False) -> None:
    rows = [entry for entry in entries if (not entry["active"]) == inactive_only]
    print(f"{'ID':<30} {'FILE':<22} {'KEY/TRIGGER':<18} {'PLATFORM':<12} {'PORTABILITY':<16} LABEL")
    print("-" * 130)
    for entry in rows:
        platforms = ",".join(str(value) for value in entry["platform"])
        print(f"{entry['id']:<30} {entry['file']:<22} {_display_key(entry):<18} {platforms:<12} {entry['portability']:<16} {entry['label']}")
    print(f"\n{len(rows)} entries")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    actions = parser.add_mutually_exclusive_group(required=True)
    actions.add_argument("--init-db", action="store_true", help="Create a new empty SQLite catalog if none exists.")
    actions.add_argument("--sync", action="store_true", help="Generate AHK and Markdown artifacts from hotkeys.db.")
    actions.add_argument("--check", action="store_true", help="Validate the catalog and detect generated artifact drift.")
    actions.add_argument("--list", action="store_true", help="List active catalog entries.")
    actions.add_argument("--list-inactive", action="store_true", help="List inactive catalog entries.")
    args = parser.parse_args()
    try:
        if args.init_db:
            create_db()
            return 0
        entries = load_db()
        if args.sync:
            sync(entries)
            return 0
        if args.check:
            return 0 if check(entries) else 1
        list_entries(entries, inactive_only=args.list_inactive)
        return 0
    except (CatalogError, sqlite3.Error, OSError) as exc:
        print(f"hotkey_sync: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    raise SystemExit(main())
