; AUTO-GENERATED by ai/hotkey_sync.py
; Human source: platforms/windows/data/hotkeys.db
; Regenerate: python ai/hotkey_sync.py --sync

#hotif winactive(exeMsTeams)
f1::{
trackDomainsHotkeyUsage("f1", "teams")
services.dynamic.openTeamsSearchAndGoToField()
}
#hotif winactive(titleWhatsapp)
f1::{
trackDomainsHotkeyUsage("f1", "whatsapp")
services.whatsapp.archive()
}
f2::{
trackDomainsHotkeyUsage("f2", "whatsapp")
services.whatsapp.delete()
}
+f1::{
trackDomainsHotkeyUsage("+f1", "whatsapp")
services.whatsapp.clearArchive()
}
#hotif
