; AUTO-GENERATED by ai/hotkey_sync.py
; Edit platforms/windows/data/hotkeys-catalog.json, then run: python ai/hotkey_sync.py --sync

#hotif winactive(exeVlc)
d::{
trackDomainsHotkeyUsage("d", "vlc")
Send("]")
}
s::{
trackDomainsHotkeyUsage("s", "vlc")
Send("[")
}
#hotif winactive(exeFirefox)
^+n::{
trackDomainsHotkeyUsage("^+n", "firefox")
Send("^+p")
}
#hotif
