; AUTO-GENERATED by ai/hotkey_sync.py
; Human source: platforms/windows/data/hotkeys.db
; Regenerate: python ai/hotkey_sync.py --sync

#hotif winactive(titleSnipaste)
~enter::{
services.snipaste.copyPaste("",snipasteTargets)
}
#hotif winactive("ahk_group group_launcher")
f12::{
services.launcher.pasteSelectedFiles()
}
^s::{
services.launcher.saveClipboardToSelectedFile()
}
!p::{
services.launcher.openSelectedMedia()
}
#hotif
