; AUTO-GENERATED by ai/hotkey_sync.py
; Edit platforms/windows/data/hotkeys-catalog.json, then run: python ai/hotkey_sync.py --sync

#hotif winactive(titleSnipaste)
~enter::{
trackDomainsHotkeyUsage("~enter", "snipaste")
services.snipaste.copyPaste("",snipasteTargets)
}
#hotif winactive("ahk_group group_launcher")
f12::{
trackDomainsHotkeyUsage("f12", "launcher")
services.launcher.pasteSelectedFiles()
}
^s::{
trackDomainsHotkeyUsage("^s", "launcher")
services.launcher.saveClipboardToSelectedFile()
}
!p::{
trackDomainsHotkeyUsage("!p", "launcher")
services.launcher.openSelectedMedia()
}
#hotif winactive(exeXyplorer)
f5::{
trackDomainsHotkeyUsage("f5", "xyplorer")
services.dynamic.refreshAndCloseXyplorerTab()
}
#hotif winactive(titleTaskTimeTracker)
f1::{
trackDomainsHotkeyUsage("f1", "task-time-tracker")
services.dynamic.copyAndRefreshAppTime()
}
#hotif
