; AUTO-GENERATED by ai/hotkey_sync.py
; Human source: platforms/windows/data/hotkeys.db
; Regenerate: python ai/hotkey_sync.py --sync

#hotif winactive(exeSublimeText)
!f1::{
trackEditorsHotkeyUsage("!f1", "sublime")
services.dynamic.openSublimeCommandPaletteByTag()
}
#hotif
