; AUTO-GENERATED by ai/hotkey_sync.py
; Human source: platforms/windows/data/hotkeys.db
; Regenerate: python ai/hotkey_sync.py --sync

#hotif winactive("ahk_group group_vscode_editors")
!f1::{
trackEditorsHotkeyUsage("!f1", "vscode-group")
services.dynamic.openEditorCommandPaletteWithPercent()
}
#hotif
