; AUTO-GENERATED by ai/hotkey_sync.py
; Human source: platforms/windows/data/hotkeys.db
; Regenerate: python ai/hotkey_sync.py --sync

#hotif winactive(exeWinword)
!6::{
trackEditorsHotkeyUsage("!6", "winword")
services.snipaste.resizeOffice("60")
}
!7::{
trackEditorsHotkeyUsage("!7", "winword")
services.snipaste.resizeOffice("70")
}
~^v::{
trackEditorsHotkeyUsage("~^v", "winword")
services.snipaste.pasteResizeOffice()
}
#hotif
