; AUTO-GENERATED by ai/hotkey_sync.py
; Edit platforms/windows/data/hotkeys-catalog.json, then run: python ai/hotkey_sync.py --sync

#hotif winactive("ahk_group group_vscode_editors")
+f1::{
trackEditorsHotkeyUsage("+f1", "vscode-group")
Send("^+o")
}
!f1::{
trackEditorsHotkeyUsage("!f1", "vscode-group")
services.dynamic.openEditorCommandPaletteWithPercent()
}
^f1::{
trackEditorsHotkeyUsage("^f1", "vscode-group")
Send("^+p")
}
#hotif
