; AUTO-GENERATED by ai/hotkey_sync.py
; Edit platforms/windows/data/hotkeys-catalog.json, then run: python ai/hotkey_sync.py --sync

:*:;;::{
utilPaste("ñ",,True)
}
:*:"+::{
services.sap.insertCommentLine()
}
:*:"-::{
services.sap.insertCommentLine()
}
:*:*+::{
services.sap.insertCommentBlock()
}
:*:*-::{
services.sap.insertCommentBlock()
}
::sp::{
utilPaste("summary in prompt",,true)
}
!e::{
trackHotkeyEvent("!e", "hotkeys/global.ahk", "global")
services.windowGroup.activateGroup(appActivationTargets,"apps_sap_workspace")
}
!a::{
trackHotkeyEvent("!a", "hotkeys/global.ahk", "global")
services.windowGroup.activateGroup(appActivationTargets,"apps_control")
}
!s::{
trackHotkeyEvent("!s", "hotkeys/global.ahk", "global")
services.windowGroup.activateGroup(appActivationTargets,"apps_support")
}
!d::{
trackHotkeyEvent("!d", "hotkeys/global.ahk", "global")
services.windowGroup.activateGroup(appActivationTargets,"apps_ide")
}
!f::{
trackHotkeyEvent("!f", "hotkeys/global.ahk", "global")
services.windowGroup.activateGroup(appActivationTargets,"apps_note")
}
f12::{
trackHotkeyEvent("f12", "hotkeys/global.ahk", "global")
services.video.control()
}
#f1::{
trackHotkeyEvent("#f1", "hotkeys/global.ahk", "global")
services.sap.openPluzDevSession()
}
#f2::{
trackHotkeyEvent("#f2", "hotkeys/global.ahk", "global")
services.sap.openPluzQasSession()
}
#f3::{
trackHotkeyEvent("#f3", "hotkeys/global.ahk", "global")
services.sap.openPluzPrdSession()
}
#esc::{
trackHotkeyEvent("#esc", "hotkeys/global.ahk", "global")
services.windows.resizeHeight()
}
#!left::{
trackHotkeyEvent("#!left", "hotkeys/global.ahk", "global")
services.windows.snapWindowLeft()
}
#!right::{
trackHotkeyEvent("#!right", "hotkeys/global.ahk", "global")
services.windows.snapWindowRight()
}
#e::{
trackHotkeyEvent("#e", "hotkeys/global.ahk", "global")
services.run.openApp(exeXyplorer)
}
#b::{
trackHotkeyEvent("#b", "hotkeys/global.ahk", "global")
services.windows.soundToggle("40","90")
}
~\::{
trackHotkeyEvent("~\", "hotkeys/global.ahk", "global")
services.windows.microphoneToggle()
}
^\::{
trackHotkeyEvent("^\", "hotkeys/global.ahk", "global")
Send("#!k")
}
xbutton2::{
trackHotkeyEvent("xbutton2", "hotkeys/global.ahk", "global")
services.snipaste.copyPaste("{printscreen}",snipasteTargets)
}
xbutton1::{
trackHotkeyEvent("xbutton1", "hotkeys/global.ahk", "global")
services.snipaste.copyPaste("^{printscreen}",snipasteTargets)
}
$^!+a::{
trackHotkeyEvent("$^!+a", "hotkeys/global.ahk", "global")
reload()
}
~^c::{
trackHotkeyEvent("~^c", "hotkeys/global.ahk", "global")
services.snipaste.ctrlC()
}
