; AUTO-GENERATED by ai/hotkey_sync.py
; Human source: platforms/shared/data/hotkeys.db
; Regenerate: python ai/hotkey_sync.py --sync

:*:;;::{
utilPaste("ñ")
}
:*:"+::{
services.sap.insertCommentLine("+")
}
:*:"-::{
services.sap.insertCommentLine("-")
}
:*:*+::{
services.sap.insertCommentBlock("+")
}
:*:*-::{
services.sap.insertCommentBlock("-")
}
!e::{
services.windowGroup.activateGroup(appActivationTargets,"apps_sap_workspace")
}
!d::{
services.windowGroup.activateGroup(appActivationTargets,"apps_ide")
}
#esc::{
services.windows.resizeHeight()
}
xbutton2::{
services.snipaste.copyPaste("{printscreen}",snipasteTargets)
}
