; AUTO-GENERATED by ai/hotkey_sync.py
; Human source: platforms/windows/data/hotkeys.db
; Regenerate: python ai/hotkey_sync.py --sync
; SAP GUI triggers only; implementation lives in library/automation/sap.ahk.

#hotif winactive("ahk_group group_sap_gui_windows")
^b::{
services.sap.focusGuiWindows()
}
!5::{
services.sap.openWorkbenchOptions()
}
!6::{
services.sap.openSe16n()
}
!7::{
services.sap.openSe37()
}
!8::{
services.sap.openSe38()
}
!9::{
services.sap.openSe09()
}
!0::{
services.sap.openSe80()
}
#hotif
