; AUTO-GENERATED by ai/hotkey_sync.py
; Human source: platforms/shared/data/hotkeys.db
; Regenerate: python ai/hotkey_sync.py --sync
; SAP GUI triggers only; implementation lives in library/automation/sap.ahk.

#hotif winactive("ahk_group group_sap_gui_windows")
^b::{
services.sap.focusGuiWindows()
}
!4::{
services.sap.runTcode("SE24")
}
!5::{
services.sap.runTcode("ED")
}
!6::{
services.sap.runTcode("SE16N")
}
!7::{
services.sap.runTcode("SE37")
}
!8::{
services.sap.runTcode("SE38")
}
!9::{
services.sap.runTcode("SE09")
}
!0::{
services.sap.runTcode("SE80")
}
#hotif
