; AUTO-GENERATED by ai/hotkey_sync.py
; Human source: platforms/windows/data/hotkeys.db
; Regenerate: python ai/hotkey_sync.py --sync
; SAP ADT/Eclipse triggers only; implementation lives in library/automation/sap.ahk.

#hotif winactive(exeEclipse)
`::{
services.sap.promptAndOpenAbapObject()
}
f1::{
services.sap.promptAndSearchAbapObject()
}
f2::{
Send("!+r")
}
^+b::{
services.sap.focusEclipseWindows()
}
^5::{
services.sap.startQuickDebug()
}
#hotif
